#!/usr/bin/env bash

source $HOME/.rvm/scripts/rvm

cd $HOME/current/

if [[ bdsm-site.gems ]] ; then
  rvm gemset import bdsm-site.gems
fi

nanoc3 co --verbose

rsync -avgz content/assets/images/ public/images/

if [[ -d content/assets/pdf ]] ; then
  rsync -avgz content/assets/pdf/ public/pdf/
fi

